services:
  web:
    build:
      context: .
      dockerfile: docker_build/src/Dockerfile
    container_name: web
    restart: unless-stopped
    env_file:
      - src/config/envs/.env.base
      - src/config/envs/.env.app-dev
      - src/config/envs/.env.postgres-prod
      - src/config/envs/.env.pgbouncer-prod
      - src/config/envs/.env.redis-prod
    ports:
      - "8000:8000"
    depends_on:
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - my_network
  nginx:
    build:
      context: .
      dockerfile: docker_build/frontend/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      web:
        condition: service_healthy
    networks:
      - my_network
  db:
    image: postgres:18.2-alpine
    container_name: db
    restart: on-failure # The policy restarts the container if the exit code indicates an error.
    env_file:
      - src/config/envs/.env.postgres-prod
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my_network
  pgbouncer:
    image: edoburu/pgbouncer:v1.25.1-p0
    container_name: pgbouncer
    env_file:
      - src/config/envs/.env.pgbouncer-prod
    ports:
      - "6432:5432"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - my_network
  redis:
    image: redis:8.2-bookworm
    container_name: redis
    restart: unless-stopped
    env_file:
    - src/config/envs/.env.redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
    - my_network
  dbtest:
    image: postgres:18.2-alpine
    container_name: db-test
    restart: on-failure # The policy restarts the container if the exit code indicates an error.
    env_file:
      - src/config/envs/.env.postgres-test
    ports:
      - "5436:5432"
    networks:
      - my_network
    profiles:
      - test
  redistest:
    image: redis:8.2-bookworm
    container_name: redis-test
    restart: unless-stopped
    env_file:
    - src/config/envs/.env.redis-dev
    ports:
      - "6378:6379"
    networks:
    - my_network
    profiles:
      - test

volumes:
  postgres_data:
  redis_data:

networks:
  my_network:
    driver: bridge
